/-
Copyright (c) 2025 Saif Ghobash. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Saif Ghobash
-/
import Mathlib.Data.Finset.Defs
import Mathlib.Data.Finite.Defs
import Mathlib.Data.Set.Finite.Basic
import CoarseSpace.Order
import CoarseSpace.CoarseEquiv.Defs

/-!
# Finitely Generated Coarse Spaces

This file defines finitely generated coarse spaces and establishes that various
constructions preserve finite generation.

## Main Definitions

* `FG X`: Type class for finitely generated coarse spaces, asserting that the coarse
  structure can be generated by a finite set of entourages.

## Main Results

* `FG.exists_single`: Every FG coarse space has a single generating entourage (the sup).
* `FG.of_single`: A coarse space generated by a single entourage is FG.
* `FG.instFGFinite`: Coarse spaces on finite types are finitely generated.
* `FG.instFGSubsingleton`: Coarse spaces on subsingleton types are FG.
* `FG.fg_top`: The discrete (top) coarse structure is FG.
* `FG.fg_bot`: The indiscrete (bottom) coarse structure is FG.
* `FG.coinduced_of_controlledMap`: Coinduced coarse structures from FG spaces are FG.
* `FG.prod`: Products of FG coarse spaces are FG.
* `FG.sup`: The supremum of two FG coarse structures is FG.

-/

open CoarseSpace Entourage

/-- A coarse space is **finitely generated** if its coarse structure can be generated
by a finite set of entourages. -/
class FG (X : Type*) [CoarseSpace X] where
  /-- There exists a finite generating set for the coarse structure. -/
  out : ∃ (S : Finset (Entourage X)), ∀ (E : Entourage X),
         IsControlled[(generateFrom S)] E ↔ IsControlled E

namespace FG

variable {X Y : Type*} [CoarseSpace X]

/-- Every finitely generated coarse space can be generated by a single entourage,
namely the supremum of any finite generating set. -/
theorem exists_single (X : Type*) [CoarseSpace X] [FG X] :
    ∃ E : Entourage X, ∀ F : Entourage X,
      IsControlled[(generateFrom {E})] F ↔ IsControlled F := by
  obtain ⟨S, hS⟩ := ‹FG X›.out
  refine ⟨S.sup id, fun F => ?_⟩
  rw [← generateFrom_finset_eq_generateFrom_sup S]
  exact hS F

/-- A coarse space generated by a single entourage is finitely generated. -/
theorem of_single (E : Entourage X)
    (h : ∀ F, IsControlled[(generateFrom {E})] F ↔ IsControlled F) : FG X :=
  ⟨{E}, fun F => (Finset.coe_singleton E ▸ h F : _)⟩

/-- The coarse structure on `X` is finitely generated iff there exists a finite
generating set. -/
theorem iff_exists_finset : FG X ↔
    ∃ (S : Finset (Entourage X)), ∀ (F : Entourage X),
       IsControlled[(generateFrom S)] F ↔ IsControlled F :=
  ⟨fun H ↦ H.out, fun h ↦ ⟨h⟩⟩

/-- Finitely generated spaces have a reflexive symmetric generator whose powers
cover all controlled sets. -/
theorem exists_refl_symm_generator (X : Type*) [CoarseSpace X] [FG X] :
    ∃ E : Entourage X, IsControlled E ∧ E.IsRefl ∧ E.IsSymm ∧
      ∀ F, IsControlled F → ∃ (n : ℕ), F ⊆ E ^ n := by
  obtain ⟨E₀, hE₀⟩ := exists_single X
  let G := E₀.symmetrize ∪ Entourage.id
  have hE₀_ctrl : IsControlled E₀ := (hE₀ E₀).mp (.basic E₀ rfl)
  have hG_ctrl : IsControlled G := (hE₀_ctrl.union hE₀_ctrl.inv).union isControlled_id
  have hG_refl : G.IsRefl := ⟨fun _ => Or.inr rfl⟩
  have hG_symm : G.IsSymm := ⟨fun x y h => h.elim
    (fun h => Or.inl ((symmetrize_isSymm E₀).symm x y h))
    (fun h => Or.inr h.symm)⟩
  exact ⟨G, hG_ctrl, hG_refl, hG_symm, fun F hF => ((hE₀ F).mpr hF).subset_pow⟩

/-- Get a reflexive symmetric generator using choice. -/
def getGenerator (X : Type*) [CoarseSpace X] [FG X] : Entourage X :=
  (exists_refl_symm_generator X).choose

section getGenerator

variable {X : Type*} [CoarseSpace X] [FG X]

theorem isControlled_getGenerator : IsControlled (getGenerator X) :=
 (FG.exists_refl_symm_generator X).choose_spec.1

theorem getGenerator_isRefl : (getGenerator X).IsRefl :=
  (FG.exists_refl_symm_generator X).choose_spec.2.1

theorem getGenerator_isSymm : (getGenerator X).IsSymm :=
  (FG.exists_refl_symm_generator X).choose_spec.2.2.1

theorem getGenerator_mem_pow :
    ∀ (E : Entourage X), IsControlled E → ∃ (n : ℕ), E ⊆ (getGenerator X) ^ n :=
  (FG.exists_refl_symm_generator X).choose_spec.2.2.2

theorem generateFrom_getGenerator_eq :
    generateFrom {FG.getGenerator X} = ‹CoarseSpace X› :=
  le_antisymm
    (generateFrom_le_iff_subset_controlled.mpr fun _ hE ↦ hE ▸ FG.isControlled_getGenerator)
    (fun E hE ↦ let ⟨n, hn⟩ := FG.getGenerator_mem_pow E hE
      (GenerateControlled.pow_single _ n).subset hn)

theorem getGenerator_symmetrize_union_id :
    (FG.getGenerator X).symmetrize ∪ Entourage.id = FG.getGenerator X := by
  rw [Entourage.symmetrize_eq_self.mpr FG.getGenerator_isSymm]
  exact Set.union_eq_left.mpr (fun ⟨a, _⟩ h => h ▸ FG.getGenerator_isRefl.1 a)

end getGenerator

/-! ### Finite and Subsingleton Types -/

/-- On a finite type, the set of controlled entourages is finite. -/
theorem finite_isControlled [Finite X] : { E : Entourage X | IsControlled E }.Finite :=
  Set.Finite.subset (Set.finite_univ) (Set.subset_univ _)

/-- A coarse space on a finite type is finitely generated. -/
instance instFGOfFinite [Finite X] : FG X :=
  ⟨finite_isControlled.toFinset, fun E => by
    rw [Set.Finite.coe_toFinset, generateFrom_setOf_isControlled]⟩

/-- A coarse space on a subsingleton type is finitely generated. -/
instance instFGSubsingleton [Subsingleton X] : FG X :=
  of_single Entourage.id fun _ =>
    ⟨fun _ => isControlled_id.subset fun ⟨x, y⟩ _ => Subsingleton.elim x y,
     fun _ => GenerateControlled.subset (.basic _ rfl) fun ⟨x, y⟩ _ => Subsingleton.elim x y⟩

/-- The empty type has a finitely generated coarse structure. -/
instance instFGEmpty : FG Empty :=
  of_single Entourage.id fun _ =>
    ⟨fun _ => trivial, fun _ => GenerateControlled.id.subset fun x _ => x.1.elim⟩

/-- The unit type has a finitely generated coarse structure. The unique coarse
structure on `Unit` is generated by the diagonal. -/
instance instFGUnit : FG Unit :=
  of_single Entourage.id fun _ =>
    ⟨fun _ => trivial, fun _ => GenerateControlled.id.subset fun ⟨a, b⟩ _ => Subsingleton.elim a b⟩

section TopBot

variable {X : Type*}

/-! ### The Discrete and Indiscrete Coarse Structures -/

/-- The discrete (top) coarse structure is finitely generated. It is generated
by `Set.univ`. -/
instance fg_top : @FG X ⊤ := @FG.of_single X ⊤ Set.univ fun F =>
  ⟨fun _ => trivial, fun _ => GenerateControlled.subset (.basic _ rfl) (Set.subset_univ F)⟩

/-- The indiscrete (bottom) coarse structure is finitely generated. It is generated
by the empty set. -/
instance fg_bot : @FG X ⊥ := @FG.mk X ⊥
  ⟨∅, fun E => by simp only [Finset.coe_empty, isControlled_bot_iff]⟩

end TopBot

section Coinduced

variable {X : Type*}

/-! ### Coinduced Coarse Structures -/

/-- The coinduced coarse structure from an FG space is FG. The generating set
for the coinduced structure is the image of the original generating set under
the map `f`. -/
theorem coinduced_of_controlledMap [cX : CoarseSpace X] [FG X] {f : X → Y} :
    @FG Y (coinduced f cX) := by
  classical
  obtain ⟨S, hS⟩ := ‹FG X›.out
  refine @FG.mk Y (coinduced f cX)
         ⟨S.image (Entourage.map f), fun F => ⟨fun hF => ?_, fun hF => ?_⟩⟩
  · apply @generateFrom_le_iff_subset_controlled Y _ (coinduced f cX) |>.mpr _ F hF
    intro E hE
    obtain ⟨E', hE', rfl⟩ := Finset.mem_image.mp hE
    exact @isControlled_coinduced_of_subset_image X Y f cX _
      ⟨E', (hS E').mp (.basic E' hE'), subset_rfl⟩
  · apply @generateFrom_le_iff_subset_controlled Y _
          (generateFrom (S.image (Entourage.map f) : Set _)) |>.mpr _ F hF
    rintro _ ⟨E, hE, hsub⟩
    rw [Finset.coe_image]
    exact ((hS E).mpr hE).map f |>.subset hsub

end Coinduced

section Prod

variable [CoarseSpace Y]

/-! ### Product Coarse Structures -/

/-- FG instance for products when the left factor is empty. Every entourage on
an empty product is empty, so the coarse structure is trivially finitely generated. -/
theorem prod_of_isEmpty_left [IsEmpty X] : @FG (X × Y) _ :=
  ⟨∅, fun E => ⟨fun _ => isControlled_prod_of_isEmpty_left E,
                fun _ => .of_isEmpty _ E⟩⟩

/-- FG instance for products when the right factor is empty. Every entourage on
an empty product is empty, so the coarse structure is trivially finitely generated. -/
theorem prod_of_isEmpty_right [IsEmpty Y] : @FG (X × Y) _ :=
  ⟨∅, fun E => ⟨fun _ => isControlled_prod_of_isEmpty_right E,
                fun _ => .of_isEmpty _ E⟩⟩

/-- The product of finitely generated coarse spaces is finitely generated.

If `S` generates the coarse structure on `X` and `T` generates the coarse structure
on `Y`, then `{ E ×ˢ id | E ∈ S } ∪ { id ×ˢ F | F ∈ T }` generates the product
coarse structure on `X × Y`. -/
instance prod [FG X] [FG Y] : FG (X × Y) := by
  cases isEmpty_or_nonempty X with
  | inl => exact prod_of_isEmpty_left
  | inr =>
    cases isEmpty_or_nonempty Y with
    | inl => exact prod_of_isEmpty_right
    | inr =>
      classical
      obtain ⟨S, hS⟩ := ‹FG X›.out
      obtain ⟨T, hT⟩ := ‹FG Y›.out
      refine ⟨S.image (· ×ˢ .id) ∪ T.image (.id ×ˢ ·), fun E => ⟨?_, ?_⟩⟩
      · apply generateFrom_le_iff_subset_controlled.mpr _ E
        simp only [Finset.coe_union, Finset.coe_image]
        rintro _ (⟨E', hE', rfl⟩ | ⟨F', hF', rfl⟩)
        · exact isControlled_sprod_id_iff.mpr ((hS E').mp (.basic E' hE'))
        · exact isControlled_id_sprod_iff.mpr ((hT F').mp (.basic F' hF'))
      · intro ⟨hE1, hE2⟩
        simp only [Finset.coe_union, Finset.coe_image]
        have h1 : GenerateControlled (↑S) (E.map Prod.fst) := (hS _).mpr hE1
        have h2 : GenerateControlled (↑T) (E.map Prod.snd) := (hT _).mpr hE2
        exact (h1.sprod h2).subset (subset_sprod_map_fst_snd E)

end Prod

section Order

variable {X : Type*}

/-! ### Order Structure -/

/-- The supremum of two FG coarse structures is FG. If `S` generates `c₁` and
`T` generates `c₂`, then `S ∪ T` generates `c₁ ⊔ c₂`. -/
theorem sup {c₁ c₂ : CoarseSpace X} [@FG X c₁] [@FG X c₂] : @FG X (c₁ ⊔ c₂) := by
  classical
  obtain ⟨S, hS⟩ := ‹@FG X c₁›.out
  obtain ⟨T, hT⟩ := ‹@FG X c₂›.out
  refine @FG.mk X (c₁ ⊔ c₂) ⟨S ∪ T, fun E => ⟨fun hE => ?_, fun hE => ?_⟩⟩
  · -- Forward: GenerateControlled (S ∪ T) E → controlled in sup
    apply @generateFrom_le_iff_subset_controlled X _ (c₁ ⊔ c₂) |>.mpr _ E hE
    rw [Finset.coe_union]
    rintro F (hF | hF)
    · exact (le_sup_left : c₁ ≤ c₁ ⊔ c₂) F ((hS F).mp (.basic F hF))
    · exact (le_sup_right : c₂ ≤ c₁ ⊔ c₂) F ((hT F).mp (.basic F hF))
  · -- Backward: controlled in sup → GenerateControlled (S ∪ T) E
    rw [Finset.coe_union]
    have hle1 : c₁ ≤ generateFrom (↑S ∪ ↑T) :=
      fun F hF => ((hS F).mpr hF).mono Set.subset_union_left
    have hle2 : c₂ ≤ generateFrom (↑S ∪ ↑T) :=
      fun F hF => ((hT F).mpr hF).mono Set.subset_union_right
    exact sup_le hle1 hle2 E hE

end Order

end FG
