/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Saif Ghobash
-/
import CoarseSpace.Basic
import CoarseSpace.Constructions

import Mathlib.Data.Finset.Lattice.Fold
import Mathlib.Data.Set.Lattice
import Mathlib.Order.GaloisConnection.Basic
/-!
# Order Structure on Coarse Spaces

This file establishes the complete lattice structure on coarse spaces via a Galois insertion
with sets of entourages, and develops the theory of generating coarse structures.

## Main Definitions

* `GenerateControlled S`: Inductive predicate for entourages generated by `S`
* `generateFrom S`: The coarsest coarse structure containing `S`
* `coinduced f cX`: The finest coarse structure making `f` controlled

## Main Results

* `CoarseSpace X` forms a `CompleteLattice`
* `gc_coinduced_induced`: Galois connection between coinduced and induced
* `controlled_iff_coinduced_le` /
  `controlled_iff_le_induced`: Characterizations of controlled maps

## Implementation Notes

The lattice structure is lifted via `giGenerateFrom`, a Galois insertion between
`generateFrom` and `fun c => { E | IsControlled[c] E }`.
-/

open Set Entourage Function Prod

open scoped Entourage

universe u v w

namespace CoarseSpace

variable {X : Type u} {Y : Type v}

/-! ### Generation of Coarse Structures -/

/-- Inductive predicate for entourages generated by a set `S`. An entourage is generated if it
can be built from elements of `S` using the coarse structure operations (subset, union, identity,
inverse, composition). -/
inductive GenerateControlled (S : Set (Entourage X)) : Entourage X → Prop
  | basic : ∀ E ∈ S, GenerateControlled S E
  | subset : ∀ {E F}, GenerateControlled S E → F ⊆ E → GenerateControlled S F
  | union : ∀ {E F}, GenerateControlled S E → GenerateControlled S F → GenerateControlled S (E ∪ F)
  | id : GenerateControlled S Entourage.id
  | inv : ∀ {E}, GenerateControlled S E → GenerateControlled S E⁻¹
  | comp : ∀ {E F}, GenerateControlled S E →
                      GenerateControlled S F → GenerateControlled S (E ○ F)

/-- On an empty type, every entourage is trivially generated by any set,
since the diagonal (and hence every entourage) is empty. -/
theorem GenerateControlled.of_isEmpty [IsEmpty X] (S : Set (Entourage X)) (E : Entourage X) :
    GenerateControlled S E :=
  id.subset fun ⟨a, _⟩ _ => (IsEmpty.false a).elim

/-- If `E` is generated by `S`, then `E.map f` is generated by `S.image (map f)`. -/
theorem GenerateControlled.map {Y} {S : Set (Entourage X)} {E : Entourage X} (f : X → Y)
    (hE : GenerateControlled S E) :
    GenerateControlled (Entourage.map f '' S) (E.map f) :=
  hE.rec
    (fun E' hE' => .basic _ ⟨E', hE', rfl⟩)
    (fun _ hsub ih => ih.subset (Entourage.map_mono f hsub))
    (fun _ _ ih1 ih2 => Entourage.map_union f _ _ ▸ ih1.union ih2)
    (id.subset fun ⟨_, _⟩ ⟨_, hz, heq⟩ => heq ▸ mem_preimage.mp (congrArg f hz))
    (fun _ ih => Entourage.map_inv _ f ▸ ih.inv)
    (fun _ _ ih1 ih2 => (ih1.comp ih2).subset (Entourage.map_comp_subset _ _ f))

/-- If `E` is generated by `S`, then `E ×ˢ id` is generated by `(· ×ˢ id) '' S`. -/
theorem GenerateControlled.sprod_id_left {S : Set (Entourage X)} {E : Entourage X}
    (hE : GenerateControlled S E) :
    GenerateControlled ((· ×ˢ Entourage.id (α := Y)) '' S) (E ×ˢ Entourage.id) := by
  induction hE with
  | basic E' hE' => exact .basic _ ⟨E', hE', rfl⟩
  | subset _ hsub ih => exact ih.subset (sprod_mono hsub le_rfl)
  | union _ _ ih1 ih2 => rw [sprod_union_left]; exact ih1.union ih2
  | id => rw [sprod_id_id]; exact .id
  | inv _ ih =>
    rw [Entourage.id] at *;
    nth_rw 2 [← SetRel.inv_id] at ih
    exact ih.inv
  | comp _ _ ih1 ih2 =>
    rw [← SetRel.id_comp (R := Entourage.id (α := Y)), ← sprod_comp]
    rw [Entourage.id_eq, SetRel.comp_id] at *
    exact ih1.comp ih2

/-- If `F` is generated by `T`, then `id ×ˢ F` is generated by `(id ×ˢ ·) '' T`. -/
theorem GenerateControlled.sprod_id_right {T : Set (Entourage Y)} {F : Entourage Y}
    (hF : GenerateControlled T F) :
    GenerateControlled ((Entourage.id (α := X) ×ˢ ·) '' T) (Entourage.id ×ˢ F) := by
  induction hF with
  | basic F' hF' => exact .basic _ ⟨F', hF', rfl⟩
  | subset _ hsub ih => exact ih.subset (sprod_mono le_rfl hsub)
  | union _ _ ih1 ih2 => rw [sprod_union_right]; exact ih1.union ih2
  | id => rw [sprod_id_id]; exact .id
  | inv _ ih =>
    rw [Entourage.id] at *
    nth_rw 2 [← SetRel.inv_id]
    exact ih.inv
  | comp _ _ ih1 ih2 =>
    rw [← SetRel.comp_id (R := Entourage.id (α := X)), ← sprod_comp]
    rw [Entourage.id_eq, SetRel.id_comp] at *
    exact ih1.comp ih2

/-- `GenerateControlled` is monotone in the generating set. -/
@[mono]
theorem GenerateControlled.mono {S T : Set (Entourage X)} {E : Entourage X}
    (hST : S ⊆ T) (hE : GenerateControlled S E) : GenerateControlled T E :=
  hE.rec
    (fun E' hE' ↦ .basic E' (hST hE'))
    (fun _ hsub ih ↦ ih.subset hsub)
    (fun _ _ ih1 ih2 ↦ ih1.union ih2)
    .id
    (fun _ ih ↦ ih.inv)
    (fun _ _ ih1 ih2 ↦ ih1.comp ih2)

/-- If `E` is generated by `S` and `F` is generated by `T`, then `E ×ˢ F` is generated by
    the union of `(· ×ˢ id) '' S` and `(id ×ˢ ·) '' T`. -/
theorem GenerateControlled.sprod {S : Set (Entourage X)} {T : Set (Entourage Y)}
    {E : Entourage X} {F : Entourage Y}
    (hE : GenerateControlled S E) (hF : GenerateControlled T F) :
    GenerateControlled ((· ×ˢ Entourage.id (α := Y)) '' S ∪ (Entourage.id (α := X) ×ˢ ·) '' T)
      (E ×ˢ F) :=
  sprod_id_comp_id_sprod E F ▸
    (hE.sprod_id_left.mono Set.subset_union_left).comp
    (hF.sprod_id_right.mono Set.subset_union_right)

/-- Powers of a single entourage are generated by that entourage. -/
theorem GenerateControlled.pow_single (E : Entourage X) (n : ℕ) :
    GenerateControlled {E} (E ^ n) :=
  n.rec .id fun _ ih => .comp (.basic _ rfl) ih

/-- Powers of a reflexive symmetric entourage absorb all coarse operations. -/
theorem exists_pow_superset_of_refl_symm {G : Entourage X} (hG_refl : G.IsRefl) (hG_symm : G.IsSymm)
    {F : Entourage X} (hF : GenerateControlled {E | E ⊆ G} F) : ∃ (n : ℕ), F ⊆ G ^ n :=
  hF.rec
    (fun _ hE ↦ ⟨1, (pow_one G).symm ▸ hE⟩)
    (fun _ hsub ih ↦ ih.imp fun _ hn ↦ hsub.trans hn)
    (fun _ _ ih₁ ih₂ ↦ ⟨max ih₁.choose ih₂.choose, Set.union_subset
      (ih₁.choose_spec.trans (pow_subset_pow hG_refl (le_max_left _ _)))
      (ih₂.choose_spec.trans (pow_subset_pow hG_refl (le_max_right _ _)))⟩)
    ⟨0, fun _ h ↦ h⟩
    (fun _ ih ↦ ⟨ih.choose, fun ⟨x, y⟩ h ↦
      (IsSymm.pow hG_symm ih.choose).symm y x (ih.choose_spec h)⟩)
    (fun _ _ ih₁ ih₂ ↦ ⟨ih₁.choose + ih₂.choose, pow_add G _ _ ▸
      fun _ ⟨z, h₁, h₂⟩ ↦ ⟨z, ih₁.choose_spec h₁, ih₂.choose_spec h₂⟩⟩)

/-- Generated entourages are contained in powers of the reflexive-symmetric closure. -/
theorem GenerateControlled.subset_pow {E F : Entourage X} (hF : GenerateControlled {E} F) :
    ∃ (n : ℕ), F ⊆ (E.symmetrize ∪ Entourage.id) ^ n := by
  let G := E.symmetrize ∪ Entourage.id
  have hG_refl : G.IsRefl := ⟨fun _ => Or.inr rfl⟩
  have hG_symm : G.IsSymm := ⟨fun x y h => h.elim
    (fun h => Or.inl ((symmetrize_isSymm E).symm x y h))
    (fun h => Or.inr h.symm)⟩
  have hmono : {E} ⊆ {E' | E' ⊆ G} := fun _ h =>
    Set.subset_union_left.trans' (Set.mem_singleton_iff.mp h ▸ subset_symmetrize _)
  exact exists_pow_superset_of_refl_symm hG_refl hG_symm (hF.mono hmono)

/-- The coarse structure generated by a set of entourages `S`. This is the coarsest (smallest)
coarse structure containing all entourages in `S`. -/
def generateFrom (S : Set (Entourage X)) : CoarseSpace X where
  IsControlled := GenerateControlled S
  isControlled_subset := GenerateControlled.subset
  isControlled_union := GenerateControlled.union
  isControlled_id := GenerateControlled.id
  isControlled_inv := GenerateControlled.inv
  isControlled_comp := GenerateControlled.comp

/-- An entourage in the generating set is controlled in the generated coarse structure. -/
theorem isControlled_generateFrom_of_mem {S : Set (Entourage X)} {E : Entourage X} (hE : E ∈ S) :
    IsControlled[generateFrom S] E :=
  GenerateControlled.basic E hE

/-! ### Lattice Structure -/

section Lattice

variable {X : Type u} {Y : Type v}

/-- Coarse spaces on a type form a partial order where `c ≤ c'` means every controlled set
in `c` is also controlled in `c'`. Equivalently, `c` is coarser than `c'`. -/
instance : PartialOrder (CoarseSpace X) where
  le c c' := ∀ E, IsControlled[c] E → IsControlled[c'] E
  le_refl c E hE := hE
  le_trans c₁ c₂ c₃ h₁₂ h₂₃ E hE := h₂₃ E (h₁₂ E hE)
  le_antisymm c₁ c₂ h₁₂ h₂₁ := by
    apply CoarseSpace.ext
    ext E
    constructor
    · intro hE; exact h₁₂ E hE
    · intro hE; exact h₂₁ E hE

/-- Characterization of the order on coarse spaces in terms of controlled sets. -/
protected theorem le_def {c c' : CoarseSpace X} :
    c ≤ c' ↔ IsControlled[c] ≤ IsControlled[c'] :=
  Iff.rfl

/-- The generated coarse structure is below `c` iff all generators are controlled in `c`.
This is the key characterization for the Galois connection. -/
theorem generateFrom_le_iff_subset_controlled {S : Set (Entourage X)} {c : CoarseSpace X} :
  generateFrom S ≤ c ↔ S ⊆ { E | IsControlled[c] E } :=
  ⟨fun h E hE ↦ h E (.basic E hE),
   fun hS _ hE ↦  GenerateControlled.rec (fun _ hE ↦ hS hE)
  (fun _ hEF hIH ↦ hIH.subset hEF)
  (fun _ _ hIHE hIHF ↦ hIHE.union hIHF) isControlled_id
  (fun _ hIH ↦ hIH.inv) (fun _ _ hIHE hIHF ↦ hIHE.comp hIHF) hE⟩

/-- Construct a coarse space from a set that is already closed under the coarse operations. -/
protected def mkOfClosure (S : Set (Entourage X)) (hS : { E | GenerateControlled S E } = S) :
    CoarseSpace X where
  IsControlled E := E ∈ S
  isControlled_subset := hS ▸ GenerateControlled.subset
  isControlled_union := hS ▸ GenerateControlled.union
  isControlled_id := hS ▸ GenerateControlled.id
  isControlled_inv := hS ▸ GenerateControlled.inv
  isControlled_comp := hS ▸ GenerateControlled.comp

/-- A coarse space constructed from a closed set equals the one generated by that set. -/
theorem mkOfClosure_sets {S : Set (Entourage X)} {hS : { E | GenerateControlled S E } = S} :
    CoarseSpace.mkOfClosure S hS = generateFrom S :=
  CoarseSpace.ext hS.symm

/-- Galois connection between generating coarse structures and extracting controlled sets. -/
theorem gc_generateFrom (X) :
  GaloisConnection generateFrom (fun c : CoarseSpace X => { E | IsControlled[c] E }) :=
    fun _ _ => generateFrom_le_iff_subset_controlled

/-- Galois insertion lifting the complete lattice structure from sets to coarse spaces.
This is the mechanism by which `CoarseSpace X` inherits its complete lattice structure. -/
def giGenerateFrom (X : Type u) :
     GaloisInsertion generateFrom (fun c : CoarseSpace X => { E | IsControlled[c] E }) where
  gc := gc_generateFrom X
  le_l_u _ E hE := GenerateControlled.basic E hE
  choice S hS :=
  CoarseSpace.mkOfClosure S <|
      Subset.antisymm hS
        (generateFrom_le_iff_subset_controlled.mp
          (show generateFrom S ≤ generateFrom S from le_rfl))
  choice_eq _ _ := mkOfClosure_sets

/-- Coarse spaces form a complete lattice via the Galois insertion with sets of entourages. -/
instance : CompleteLattice (CoarseSpace X) := (giGenerateFrom X).liftCompleteLattice

/-- `generateFrom` is monotone: larger generating sets produce larger coarse structures. -/
@[mono, gcongr]
theorem generateFrom_mono {X} {S₁ S₂ : Set (Entourage X)} (h : S₁ ⊆ S₂) :
    generateFrom S₁ ≤ generateFrom S₂ :=
  (gc_generateFrom _).monotone_l h

/-- Generating from the controlled sets of a coarse space recovers that space. -/
@[simp]
theorem generateFrom_setOf_isControlled (c : CoarseSpace X) :
    generateFrom { E : Entourage X | IsControlled[c] E } = c :=
  (giGenerateFrom X).l_u_eq c

/-- The map extracting controlled sets is a right inverse to `generateFrom`. -/
theorem rightInverse_setOf_isControlled_generateFrom :
    RightInverse (fun c : CoarseSpace X => { E  | IsControlled[c] E }) generateFrom :=
    (giGenerateFrom X).leftInverse_l_u

/-- `generateFrom` is a left inverse to extracting controlled sets. -/
theorem leftInverse_generateFrom_setOf_isControlled :
    LeftInverse generateFrom fun c : CoarseSpace X => { E | IsControlled[c] E } :=
        (giGenerateFrom X).leftInverse_l_u

/-- Every coarse space can be generated from some set of entourages. -/
theorem generateFrom_surjective : Surjective (generateFrom : Set (Entourage X) → CoarseSpace X) :=
  (giGenerateFrom X).l_surjective

/-- Two coarse spaces with the same controlled sets are equal. -/
theorem setOf_isControlled_injective :
  Injective fun c : CoarseSpace X => { E | IsControlled[c] E } :=
  (giGenerateFrom X).u_injective

/-- If a generating set `S` admits a family `F : ι → Entourage X` such that:
- Every generator is contained in some `F i`
- `id ⊆ F i` for some `i`
- `F` is closed under union, inverse, and composition (up to containment)
Then every controlled entourage is contained in some `F i`. -/
theorem exists_superset_of_isControlled_generateFrom
    {ι : Type*} (F : ι → Entourage X) {S : Set (Entourage X)}
    (hgen : ∀ E ∈ S, ∃ i, E ⊆ F i)
    (hid : ∃ i, Entourage.id ⊆ F i)
    (hunion : ∀ i j, ∃ k, F i ∪ F j ⊆ F k)
    (hinv : ∀ i, ∃ j, (F i)⁻¹ ⊆ F j)
    (hcomp : ∀ i j, ∃ k, F i ○ F j ⊆ F k)
    {E : Entourage X} (hE : IsControlled[generateFrom S] E) :
    ∃ i, E ⊆ F i := hE.rec
    (fun _ hE => hgen _ hE)
    (fun _ hsub ih => ih.imp fun _ hi => hsub.trans hi)
    (fun _ _ ih₁ ih₂ =>
      let ⟨i, hi⟩ := ih₁; let ⟨j, hj⟩ := ih₂; let ⟨k, hk⟩ := hunion i j
      ⟨k, Set.union_subset (hi.trans (Set.subset_union_left.trans hk))
                           (hj.trans (Set.subset_union_right.trans hk))⟩)
    (hid.imp fun _ hi => hi)
    (fun _ ih => let ⟨i, hi⟩ := ih; let ⟨j, hj⟩ := hinv i; ⟨j, (SetRel.inv_mono hi).trans hj⟩)
    (fun _ _ ih₁ ih₂ =>
      let ⟨i, hi⟩ := ih₁; let ⟨j, hj⟩ := ih₂; let ⟨k, hk⟩ := hcomp i j
      ⟨k, (SetRel.comp_subset_comp hi hj).trans hk⟩)

theorem isControlled_iff_subset_pow_of_generateFrom [CoarseSpace X] (S : Finset (Entourage X))
    (hS : generateFrom (S : Set (Entourage X)) = ‹CoarseSpace X›) (E : Entourage X) :
    IsControlled E ↔ ∃ (n : ℕ), E ⊆ ((S.sup id).symmetrize ∪ Entourage.id) ^ n :=
  let G := (S.sup id).symmetrize ∪ Entourage.id
  have hG_refl : G.IsRefl := ⟨fun _ ↦ Or.inr rfl⟩
  have hG_symm : G.IsSymm := ⟨fun x y h ↦ h.elim
    (fun h ↦ Or.inl ((symmetrize_isSymm _).symm x y h))
    (fun h ↦ Or.inr h.symm)⟩
  have hS_le_G : ∀ F ∈ (S : Set (Entourage X)), F ⊆ G := fun _ hF ↦
    ((Finset.le_sup (f := id) hF).trans (subset_symmetrize _)).trans Set.subset_union_left
  have hG_controlled : IsControlled[generateFrom (S : Set (Entourage X))] G :=
    letI := generateFrom (S : Set (Entourage X))
    have hSup : IsControlled (S.sup id) :=
      isControlled_finset_sup S fun _ hF ↦ isControlled_generateFrom_of_mem hF
    (hSup.union hSup.inv).union isControlled_id
  ⟨fun hE ↦ exists_pow_superset_of_refl_symm hG_refl hG_symm ((hS ▸ hE).mono hS_le_G),
   fun ⟨n, hn⟩ ↦
     letI := generateFrom (S : Set (Entourage X))
     hS ▸ (hG_controlled.pow n).subset hn⟩

theorem isControlled_sup_of_generateFrom [CoarseSpace X] (S : Finset (Entourage X))
    (hS : generateFrom (S : Set _) = ‹CoarseSpace X›) : IsControlled (S.sup id) :=
  hS ▸ @isControlled_finset_sup X (generateFrom S) S fun _ hE => isControlled_generateFrom_of_mem hE

end Lattice

/-! ### Infimum and Supremum Properties -/

section iInf

variable {X : Type u} {ι : Sort*}

/-- Generation commutes with union, giving the supremum. -/
theorem generateFrom_union (S T : Set (Entourage X)) :
  generateFrom (S ∪ T) = generateFrom S ⊔ generateFrom T :=
  (gc_generateFrom X).l_sup

/-- Controlled sets of an infimum are the intersection of controlled sets. -/
theorem setOf_isControlled_inf (c₁ c₂ : CoarseSpace X) :
  { E | IsControlled[c₁ ⊓ c₂] E } = { E | IsControlled[c₁] E } ∩ { E | IsControlled[c₂] E } :=
  (gc_generateFrom X).u_inf

/-- Generation commutes with indexed union, giving the indexed supremum. -/
theorem generateFrom_iUnion (F : ι → Set (Entourage X)) :
  generateFrom (⋃ i, F i) = ⨆ i, generateFrom (F i) :=
  (gc_generateFrom X).l_iSup

/-- Controlled sets of an indexed infimum are the indexed intersection. -/
theorem setOf_isControlled_iInf (C : ι → CoarseSpace X) :
  { E | IsControlled[iInf C] E } = ⋂ i, { E | IsControlled[C i] E } :=
  (gc_generateFrom X).u_iInf

/-- Generation commutes with set union, giving the indexed supremum over the set. -/
theorem generateFrom_sUnion (𝒮 : Set (Set (Entourage X))) :
  generateFrom (⋃₀ 𝒮) = ⨆ T ∈ 𝒮, generateFrom T :=
  (gc_generateFrom X).l_sSup

/-- If `S` is a finite set of entourages, then `generateFrom S = generateFrom {S.sup id}`. -/
theorem generateFrom_finset_eq_generateFrom_sup (S : Finset (Entourage X)) :
    generateFrom (S : Set (Entourage X)) = generateFrom {S.sup id} := by
  apply le_antisymm
  -- (≤) Each element of S is a subset of S.sup id
  · apply generateFrom_le_iff_subset_controlled.mpr
    intro E hE
    exact GenerateControlled.subset (GenerateControlled.basic _ rfl)
      (Finset.le_sup (f := id) hE)
  -- (≥) S.sup id is a finite union of generators, hence controlled in generateFrom S
  · apply generateFrom_le_iff_subset_controlled.mpr
    intro E hE
    rw [mem_singleton_iff] at hE
    rw [hE]
    exact @isControlled_finset_sup X (generateFrom ↑S) S
      fun F hF => GenerateControlled.basic F hF

/-- Controlled sets of a set infimum are the indexed intersection over the set. -/
theorem setOf_isControlled_sInf (𝒞 : Set (CoarseSpace X)) :
  { E | IsControlled[sInf 𝒞] E } = ⋂ c ∈ 𝒞, { E | IsControlled[c] E } :=
  (gc_generateFrom X).u_sInf

/-- The supremum of two coarse spaces is generated by the union of their controlled sets. -/
theorem generateFrom_union_isControlled (c₁ c₂ : CoarseSpace X) :
  generateFrom ({ E | IsControlled[c₁] E } ∪ { E | IsControlled[c₂] E }) = c₁ ⊔ c₂ := by
  simpa [generateFrom_setOf_isControlled] using
    (generateFrom_union { E | IsControlled[c₁] E } { E | IsControlled[c₂] E })

/-- The indexed supremum is generated by the indexed union of controlled sets. -/
theorem generateFrom_iUnion_isControlled (C : ι → CoarseSpace X) :
  generateFrom (⋃ i, { E | IsControlled[C i] E }) = ⨆ i, C i := by
  simpa [generateFrom_setOf_isControlled] using
    (generateFrom_iUnion (F := fun i => { E | IsControlled[C i] E }))

/-- The infimum of two coarse spaces is generated by the intersection of their controlled sets. -/
theorem generateFrom_inter_isControlled (c₁ c₂ : CoarseSpace X) :
  generateFrom ({ E | IsControlled[c₁] E } ∩ { E | IsControlled[c₂] E }) = c₁ ⊓ c₂ :=
  setOf_isControlled_inf (c₁ := c₁) (c₂ := c₂) ▸ generateFrom_setOf_isControlled (c := c₁ ⊓ c₂)

/-- The indexed infimum is generated by the indexed intersection of controlled sets. -/
theorem generateFrom_iInter_isControlled (C : ι → CoarseSpace X) :
  generateFrom (⋂ i, { E : Entourage X | IsControlled[C i] E }) = ⨅ i, C i :=
  setOf_isControlled_iInf (C := C) ▸ generateFrom_setOf_isControlled (c := iInf C)

/-- Generation from an indexed intersection when each set is already closed. -/
theorem generateFrom_iInter_of_generateFrom_eq_self
  (F : ι → Set (Entourage X)) (hF : ∀ i, { E | IsControlled[generateFrom (F i)] E } = F i) :
  generateFrom (⋂ i, F i) = ⨅ i, generateFrom (F i) := by
  have h_sets :
      { E : Entourage X | IsControlled[iInf (fun i => generateFrom (F i))] E } =
        ⋂ i, F i := by simpa [hF] using (setOf_isControlled_iInf (C := fun i => generateFrom (F i)))
  simpa [h_sets] using generateFrom_setOf_isControlled (c := iInf fun i => generateFrom (F i))

/-- An entourage is controlled in an indexed infimum iff it is controlled in each component. -/
@[simp]
theorem isControlled_iInf_iff (C : ι → CoarseSpace X) (E : Entourage X) :
  IsControlled[iInf C] E ↔ ∀ i, IsControlled[C i] E := by
   change E ∈ {E | IsControlled[iInf C] E} ↔ _
   simp only [setOf_isControlled_iInf (C := C), mem_iInter, mem_setOf_eq]

/-- An entourage is controlled in a set infimum iff it is controlled in each member. -/
@[simp]
theorem isControlled_sInf_iff (𝒞 : Set (CoarseSpace X)) (E : Entourage X) :
  IsControlled[sInf 𝒞] E ↔ ∀ c ∈ 𝒞, IsControlled[c] E := by
  change E ∈ { E : Entourage X | IsControlled[sInf 𝒞] E } ↔ _
  simp only [setOf_isControlled_sInf (𝒞 := 𝒞), mem_iInter, mem_setOf_eq]

end iInf

/-! ### Top and Bottom Coarse Structures -/

section TopBot

variable {X : Type u}

/-- The bottom coarse structure is generated by the empty set. -/
theorem bot_eq_generateFrom_empty : (⊥ : CoarseSpace X) = generateFrom ∅ :=
  (gc_generateFrom X).l_bot.symm

/-- An entourage is controlled in `⊥` iff it's generated from the diagonal alone. -/
@[simp]
theorem isControlled_bot_iff {E : Entourage X} :
    IsControlled[(⊥ : CoarseSpace X)] E ↔ GenerateControlled ∅ E := by
  rw [bot_eq_generateFrom_empty]; rfl

/-- Subsets of the diagonal are controlled in `⊥`. -/
theorem isControlled_bot_of_subset_id {E : Entourage X} (h : E ⊆ Entourage.id) :
    IsControlled[(⊥ : CoarseSpace X)] E :=
  isControlled_bot_iff.mpr (GenerateControlled.subset GenerateControlled.id h)

/-- The diagonal is controlled in `⊥`. -/
@[simp]
theorem isControlled_bot_id : IsControlled[(⊥ : CoarseSpace X)] Entourage.id :=
  isControlled_bot_iff.mpr GenerateControlled.id

/-- The top coarse structure is generated by `Set.univ`. -/
theorem top_eq_generateFrom_univ : (⊤ : CoarseSpace X) = generateFrom Set.univ :=
  le_antisymm (fun E _ ↦ GenerateControlled.basic E (mem_univ E)) le_top

/-- Every entourage is controlled in the top coarse structure. -/
@[simp]
theorem isControlled_top (E : Entourage X) : IsControlled[(⊤ : CoarseSpace X)] E := by
  rw [top_eq_generateFrom_univ]; exact GenerateControlled.basic E (mem_univ E)

/-- Every set is coarsely bounded in the top (indiscrete) coarse structure. -/
theorem isCoarselyBounded_top (s : Set X) : IsCoarselyBounded[⊤] s :=
  @IsCoarselyBounded.mk X ⊤ s (isControlled_top _)

/-- Entourages generated from the empty set are subsets of the diagonal. -/
theorem GenerateControlled_empty_subset_id {E : Entourage X} (h : GenerateControlled ∅ E) :
    E ⊆ Entourage.id := by
  induction h with
  | basic _ hE => exact (Set.notMem_empty _ hE).elim
  | subset _ hFE ih => exact fun x hx ↦ ih (hFE hx)
  | union _ _ ih₁ ih₂ => exact Set.union_subset ih₁ ih₂
  | id => exact le_rfl
  | inv _ ih => intro ⟨x, y⟩ hxy; exact (ih hxy).symm
  | comp _ _ ih₁ ih₂ => intro ⟨x, y⟩ ⟨z, hxz, hzy⟩; exact (ih₁ hxz).trans (ih₂ hzy)

/-- A set is coarsely bounded in `⊥` iff it's a subsingleton. -/
theorem isCoarselyBounded_bot_iff {s : Set X} :
    IsCoarselyBounded[⊥] s ↔ s.Subsingleton := by
  constructor
  · rintro ⟨h⟩
    intro x hx y hy
    exact GenerateControlled_empty_subset_id
          (isControlled_bot_iff.mp h) (⟨hx, hy⟩ : (x, y) ∈ s ×ˢ s)
  · intro h
    exact @IsCoarselyBounded.mk X ⊥ s (isControlled_bot_of_subset_id fun p hp ↦ h hp.1 hp.2)

/-- The top (indiscrete) coarse structure on any type is coarsely bounded,
since the universe itself is coarsely bounded. -/
instance instCoarselyBoundedSpaceTop :
    @CoarselyBoundedSpace X ⊤ :=
    @CoarselyBoundedSpace.mk X ⊤ (isCoarselyBounded_top Set.univ)

end TopBot

/-! ### Coinduced Coarse Structure -/

section Coinduced

variable {X : Type u} {Y : Type v}

/-- The coinduced coarse structure on `Y` via `f : X → Y`. This is the finest
coarse structure on `Y` making `f` a controlled map. An entourage `F` on `Y` is controlled
iff it is contained in the image of some controlled entourage on `X`. -/
def coinduced (f : X → Y) (cX : CoarseSpace X) : CoarseSpace Y :=
  generateFrom { F | ∃ E, IsControlled E ∧ F ⊆ E.map f }

/-- Type class version of `coinduced` that uses the coarse structure from the instance.
This is convenient when working with implicit coarse structures. -/
abbrev coinducedTC {X Y} [cX : CoarseSpace X] (f : X → Y) :
  CoarseSpace Y := CoarseSpace.coinduced f cX

variable {X : Type u} {Y : Type v} (f : X → Y)
variable (cX : CoarseSpace X) (cY : CoarseSpace Y)

/-- An entourage contained in the image of a controlled entourage is controlled
in the coinduced structure. -/
theorem isControlled_coinduced_of_subset_image
  (cX : CoarseSpace X) {F : Entourage Y}
  (hF : ∃ E : Entourage X, IsControlled[cX] E ∧ F ⊆ E.map f) :
  IsControlled[CoarseSpace.coinduced f cX] F := by
  simpa [CoarseSpace.coinduced] using
    (isControlled_generateFrom_of_mem hF)

/-- The image of a controlled entourage is controlled in the coinduced structure. -/
lemma isControlled_image_of_isControlled
  {E : Entourage X} (hE : IsControlled[cX] E) :
  IsControlled[CoarseSpace.coinduced f cX] (E.map f) :=
  isControlled_coinduced_of_subset_image (f := f) cX ⟨E, hE, subset_rfl⟩

lemma isCoarselyBounded_preimage_of_coinduced (f : X → Y) {s : Set Y}
    (hs : IsCoarselyBounded[.coinducedTC f] s)
    (hcomap : ∀ E, IsControlled[.coinducedTC f] E → IsControlled (E.comap f)) :
    IsCoarselyBounded (f ⁻¹' s) := by
    let _ : CoarseSpace Y := .coinducedTC f
    exact ⟨preimage_prod_map_prod f f s s ▸ hcomap _ hs.isControlled⟩

/-- Coinduced is monotone: finer source structures give finer coinduced structures. -/
@[mono, gcongr]
theorem coinduced_mono {cX cX' : CoarseSpace X} (h : cX ≤ cX') :
  coinduced f cX ≤ coinduced f cX' :=
  (generateFrom_le_iff_subset_controlled).mpr
  (fun | _, ⟨E, hE, hsub⟩ => isControlled_coinduced_of_subset_image _ _ ⟨E, h _ hE, hsub⟩)

/-- If `f` is a controlled map, then the coinduced structure is below the target structure. -/
theorem Controlled.coinduced_le (hf : @Controlled X Y cX cY f) :
  coinduced f cX ≤ cY :=
  (generateFrom_le_iff_subset_controlled).mpr
  (fun | _, ⟨_, hE, hsub⟩ => (hf hE).subset hsub)

/-- A map is controlled iff the coinduced structure is below the target structure. -/
@[simp]
theorem controlled_iff_coinduced_le :
  @Controlled X Y cX cY f ↔ coinduced f cX ≤ cY :=
  ⟨Controlled.coinduced_le _ _ _,
   fun h ↦ fun hE ↦ h _ <| isControlled_image_of_isControlled _ _ hE⟩

theorem isControlled_comap_of_coinducedTC [CoarseSpace X] (f : X → Y)
    (hf : Function.Surjective f)
    (h_id : IsControlled ((@Entourage.id Y).comap f))
    (h_basic : ∀ E, IsControlled E → IsControlled ((E.map f).comap f))
    {F : Entourage Y} (hF : IsControlled[.coinducedTC f] F) :
    IsControlled (F.comap f) := hF.rec
    (fun _ ⟨E, hE, hFE⟩ => (h_basic E hE).subset (comap_mono _ hFE))
    (fun _ hsub ih => ih.subset (comap_mono _ hsub))
    (fun _ _ ih₁ ih₂ => comap_union _ _ _ ▸ ih₁.union ih₂)
    h_id
    (fun _ ih => comap_inv _ _ ▸ ih.inv)
    (fun _ _ ih₁ ih₂ => (ih₁.comp ih₂).subset (comap_comp_eq_of_surjective f hf _ _).subset)

end Coinduced

/-! ### Induced Coarse Structure (Order Properties) -/

section Induced

variable {X : Type u} {Y : Type v} (f : X → Y)
variable (cX : CoarseSpace X) (cY : CoarseSpace Y)

/-- Induced is monotone: coarser target structures give coarser induced structures. -/
@[mono, gcongr]
theorem induced_mono {cY' : CoarseSpace Y} (h : cY ≤ cY') :
  induced f cY ≤ induced f cY' := fun E hE ↦
    (isControlled_induced_iff (f := f) cY' E).mpr
      (h _ ((isControlled_induced_iff (f := f) cY E).mp hE))

/-- If `f` is a controlled map, then the source structure is below the induced structure. -/
theorem Controlled.le_induced
    (hf : @Controlled X Y cX cY f) :
    cX ≤ induced f cY := by
  intro E hE
  simpa [isControlled_induced_iff (f := f) (c := cY)] using hf hE

/-- A map is controlled iff the source structure is below the induced structure. -/
@[simp]
theorem controlled_iff_le_induced :
    @Controlled X Y cX cY f
      ↔ cX ≤ induced f cY :=
  ⟨Controlled.le_induced (f := f) (cX := cX) (cY := cY),
   fun h ↦ fun hE ↦ (isControlled_induced_iff (f := f) (c := cY) _).mp <| h _ hE⟩

/-- If the induced structure is below the source structure, then `f` is coarsely proper. -/
theorem coarselyProper_of_induced_le {f} (h : CoarseSpace.induced f cY ≤ cX) :
  CoarselyProper f := fun hs ↦
  ⟨h _ <| (isControlled_induced_iff cY _).mpr <| hs.isControlled.subset
    fun _ ⟨_, ⟨ha, hb⟩, heq⟩ ↦ heq ▸ ⟨ha, hb⟩⟩

end Induced

/-! ### Galois Connection Between Coinduced and Induced -/

variable {X : Type u} {Y : Type v} (f : X → Y)

/-- Coinduced and induced form a Galois connection. -/
theorem gc_coinduced_induced :
  GaloisConnection (coinduced f) (induced f) :=
  fun _ _ ↦
  ⟨fun h ↦ (controlled_iff_le_induced _ _ _).mp
      ((controlled_iff_coinduced_le _ _ _).mpr h),
   fun h ↦ (controlled_iff_coinduced_le _ _ _).mp
      ((controlled_iff_le_induced _ _ _).mpr h)⟩

/-! ### Functoriality of Induced and Coinduced -/

section IdComp

/-- Inducing by the identity gives the same coarse structure. -/
@[simp]
theorem induced_id (c : CoarseSpace X) :
  induced (fun x : X => x) c = c :=
  CoarseSpace.ext <| funext fun E ↦ propext
  ⟨fun hE ↦ (congrArg IsControlled
              <| (image_congr (fun _ _ ↦ rfl)).trans (image_id' E)).mp
              <| (isControlled_induced_iff c E).mp hE,
   fun hE ↦ (isControlled_induced_iff c E).mpr
              <| (id (congrArg IsControlled
              <| (image_congr fun _ _ ↦ rfl).trans (image_id' E))).mpr hE⟩

variable {γ : Type w}

/-- Inducing by a composition is the same as inducing twice. -/
@[simp]
theorem induced_comp (g : Y → γ) (f : X → Y) (cγ : CoarseSpace γ) :
  induced (g ∘ f) cγ = induced f (induced g cγ) :=
  CoarseSpace.ext <| funext fun _ ↦ propext
  ⟨fun hE ↦ (isControlled_induced_iff _ _).mpr
         <| (isControlled_induced_iff _ _).mpr
         <| (id (congrArg IsControlled (image_image _ _ _))).mpr
         <| (isControlled_induced_iff _ _).mp hE,
  (fun hE ↦ (isControlled_induced_iff _ _).mpr
         <| (congrArg CoarseSpace.IsControlled (image_image _ (map f f) _)).mp
         <| (isControlled_induced_iff _ _).mp
         <| (isControlled_induced_iff _ _).mp hE)⟩

/-- Inducing by a constant function gives the top (indiscrete) coarse structure,
since preimages of entourages under constant maps contain all pairs. -/
theorem induced_const_eq_top (b : Y) (cY : CoarseSpace Y) :
    induced (fun _ : X => b) cY = ⊤ :=
  top_unique fun _ _ ↦ (isControlled_induced_iff _ _).mpr <|
  (isControlled_diag_singleton b).subset fun _ ⟨_, _, h⟩ ↦ mem_singleton_of_eq <| id h.symm

/-- Coinducing by the identity gives the same coarse structure. -/
@[simp]
theorem coinduced_id (c : CoarseSpace X) :
  coinduced id c = c :=
  le_antisymm ((id ge_iff_le).mpr
            <| (congrArg (fun x ↦ coinduced id x ≤ c) (induced_id c)).mp
            <| GaloisConnection.l_u_le (gc_coinduced_induced id) c)
              ((id ge_iff_le).mpr
            <| (congrArg _ (induced_id _)).mp
            <| GaloisConnection.le_u_l (gc_coinduced_induced id) c)

/-- Coinducing by a composition is the same as coinducing twice. -/
@[simp]
theorem coinduced_comp {Z : Type w} (g : Y → Z) (f : X → Y) :
  coinduced (g ∘ f) = coinduced g ∘ coinduced f :=
  have gc₁ := gc_coinduced_induced (g ∘ f);
  have gc₂ := (gc_coinduced_induced f).compose (gc_coinduced_induced g);
  funext fun _ ↦ GaloisConnection.l_unique gc₁ gc₂ (fun cγ ↦ id (induced_comp g f cγ))

end IdComp


section Controlled

variable {X : Type u} (c₁ c₂ : CoarseSpace X)

/-- The identity is a controlled map iff the source structure is below the target. -/
@[simp]
theorem controlled_id_iff_le :
  @Controlled X X c₁ c₂ id ↔ c₁ ≤ c₂ :=
  ⟨fun h _ hE ↦ (congrArg IsControlled
             <| (image_congr fun _ _ ↦ rfl).trans
             <| image_id' _).mp
             <| h hE,
  (fun h {E} hE ↦ (id (congrArg IsControlled
             <| (image_congr fun _ _ ↦ rfl).trans
             <| image_id' E)).mpr
             <| h E hE)⟩

/-- The identity is a controlled map when the source is below the target. -/
theorem controlled_id_of_le (h : c₁ ≤ c₂) :
  @Controlled X X c₁ c₂ id :=
  (controlled_id_iff_le (c₁ := c₁) (c₂ := c₂)).mpr h

/-- A map from a generated coarse space is controlled iff it maps each generator to
a controlled entourage. This provides a useful criterion for checking that a map is
controlled when the domain has a coarse structure specified by generators. -/
theorem controlled_generateFrom (f : X → Y)
  (S : Set (Entourage X)) [CoarseSpace Y]
  (hf : ∀ E ∈ S, IsControlled (E.map f)) :
  @Controlled X Y (generateFrom S) _ f :=
  fun hE ↦ hE.recOn
  (fun E₁ hE₁ ↦ hf E₁ hE₁)
  (fun _ hFE hF => hF.subset (fun | _, ⟨q, hq, h_map⟩ => ⟨q, hFE hq, h_map⟩))
  (fun _ _ hIHE hIHF => map_union _ _ _ ▸ (hIHE.union hIHF))
  (isControlled_id.subset (image_subset_iff.mpr fun _ ↦ congrArg _))
  (fun _ hIH => map_inv _ _ ▸ hIH.inv)
  (fun _ _ hIHE hIHF => (hIHE.comp hIHF).subset (map_comp_subset _ _ _))

end Controlled

end CoarseSpace

/-! ### Monotonicity of Controlled Sets -/

section Lattice

open CoarseSpace

variable {X : Type u} {c₁ c₂ : CoarseSpace X} {E : Entourage X}

/-- Controlled sets are monotone with respect to the coarse structure order:
if `E` is controlled in `c₁` and `c₁ ≤ c₂`, then `E` is controlled in `c₂`. -/
@[mono]
theorem IsControlled.mono (hE : IsControlled[c₁] E) (h : c₁ ≤ c₂) :
    IsControlled[c₂] E := h E hE

end Lattice
