/-
Copyright (c) 2024. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Saif Ghobash
-/

import Mathlib.Algebra.Group.End
import Mathlib.Algebra.Group.Pointwise.Finset.Basic
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Algebra.Group.Units.Equiv
import Mathlib.Data.Finset.Lattice.Basic
import Mathlib.GroupTheory.Finiteness

import CoarseSpace.CoarseEquiv.Defs
import CoarseSpace.Connected
import CoarseSpace.Finiteness
import CoarseSpace.Order

/-!
# The Coarse Structure on Groups

This file defines the canonical coarse structure on a group `G`, generated by left multiplication
entourages of finite sets.

## Relationship to Word Metrics

This is the coarse-geometric analogue of equipping a group with a word metric. However, there
is a crucial difference: word metrics depend on a choice of finite generating set, so there is
no canonical word metric on a group. In contrast, the coarse structure defined here is unique—it
is simply the coarse structure generated by all finite sets, with no choices involved.

This uniqueness justifies declaring the coarse structure as a typeclass instance
(`instCoarseSpaceLeftMulRel`). Different finite generating sets yield different word metrics,
but they all induce the same coarse structure.

## Main Definitions

* `leftMulEntourage s`: the entourage `{(x, y) | x⁻¹ * y ∈ s}` associated to a set `s`.
* `leftMulGenerators G`: the set of entourages `leftMulEntourage K` for finite `K`.
* `instCoarseSpaceLeftMulRel`: the canonical coarse structure on `G`, generated by
  `leftMulGenerators G`.
* `leftMulCoarseEquiv g`: left multiplication by `g` as a coarse equivalence.
* `conjCoarseEquiv g`: conjugation by `g` as a coarse equivalence.

## Main Results

* `exists_finset_leftMulEntourage_of_isControlled`: every controlled entourage is contained
  in `leftMulEntourage K` for some finite `K`.
* `isCoarselyBounded_iff_finite`: a set is coarsely bounded iff it is finite.
* `controlled_leftMul`, `controlled_conj`: left multiplication and conjugation are controlled.
* `instGroupFG`: a group that is finitely generated as a coarse space (`FG G`) is finitely
  generated as a group (`Group.FG G`).
* `instCoarselyConnectedSpaceLeftMulRel`: the left multiplication coarse structure is
  coarsely connected.

## Tags

coarse geometry, group theory, word metric, coarse structure

## References

* J. Roe, *Lectures on Coarse Geometry*, University Lecture Series 31, AMS, 2003
-/


open Set Entourage Function Prod

open scoped Entourage Pointwise

namespace CoarseSpace

variable {G : Type*} [Group G]

/-- The left multiplication entourage associated to a set `s` in a group `G`.
This is the entourage consisting of all pairs `(x, y)` such that `x⁻¹ * y ∈ s`. -/
@[to_additive
/-- The left addition entourage associated to a set `s` in an additive group `G`.
This is the entourage consisting of all pairs `(x, y)` such that `-x + y ∈ s`. -/]
def leftMulEntourage (s : Set G) : Entourage G :=
  { p | p.1⁻¹ * p.2 ∈ s }

@[to_additive, simp]
lemma mem_leftMulEntourage {s : Set G} {x y : G} :
    (x, y) ∈ leftMulEntourage s ↔ x⁻¹ * y ∈ s :=
  Iff.rfl

@[to_additive, simp]
lemma leftMulEntourage_univ :
  leftMulEntourage (Set.univ : Set G) = (⊤ : Entourage G) :=
  rfl

@[to_additive, simp]
lemma leftMulEntourage_singleton_one :
  leftMulEntourage ({1} : Set G) = Entourage.id := by
  ext ⟨x, y⟩
  simp only [mem_leftMulEntourage, mem_singleton_iff, Entourage.mem_id]
  exact inv_mul_eq_one

@[to_additive, simp]
lemma leftMulEntourage_one :
  leftMulEntourage (1 : Set G) = Entourage.id := by
  rw [singleton_one.symm]
  exact leftMulEntourage_singleton_one

@[to_additive, simp]
lemma leftMulEntourage_empty : leftMulEntourage (∅ : Set G) = ∅ := by
  ext ⟨x, y⟩; simp

@[to_additive, gcongr]
lemma leftMulEntourage_mono {s t : Set G} (h : s ⊆ t) :
    leftMulEntourage s ⊆ leftMulEntourage t :=
  fun _ hp ↦ h hp

@[to_additive]
lemma leftMulEntourage_union (s t : Set G) :
    leftMulEntourage (s ∪ t) = leftMulEntourage s ∪ leftMulEntourage t := rfl

@[to_additive]
lemma leftMulEntourage_inter (s t : Set G) :
    leftMulEntourage (s ∩ t) = leftMulEntourage s ∩ leftMulEntourage t := rfl

@[to_additive, simp]
lemma leftMulEntourage_inv (s : Set G) :
    SetRel.inv (leftMulEntourage s) = leftMulEntourage s⁻¹ := by
  ext ⟨x, y⟩
  simp only [SetRel.mem_inv, mem_leftMulEntourage, Set.mem_inv, inv_inv, mul_inv_rev]

/-- Composition of left multiplication entourages corresponds to pointwise multiplication of
sets. -/
@[to_additive
/-- Composition of left addition entourages corresponds to pointwise addition of sets. -/]
lemma leftMulEntourage_comp (s t : Set G) :
    leftMulEntourage s ○ leftMulEntourage t = leftMulEntourage (s * t) := by
  ext ⟨x, y⟩
  simp only [SetRel.mem_comp, mem_leftMulEntourage, Set.mem_mul]
  constructor
  · rintro ⟨z, hs, ht⟩
    exact ⟨x⁻¹ * z, hs, z⁻¹ * y, ht, by rw [mul_assoc, ← mul_assoc z _, mul_inv_cancel, one_mul]⟩
  · rintro ⟨a, ha, b, hb, hab⟩
    refine ⟨x * a, ?_, ?_⟩
    · simp only [inv_mul_cancel_left]; exact ha
    · rw [mul_inv_rev, mul_assoc, ← hab, inv_mul_cancel_left]; exact hb

/-- Powers of left multiplication entourages correspond to powers of sets. -/
@[to_additive
/-- Multiples of left addition entourages correspond to multiples of sets. -/]
lemma leftMulEntourage_pow (K : Set G) (n : ℕ) :
    leftMulEntourage (K ^ n) = (leftMulEntourage K) ^ n  := by
  induction n with
  | zero =>
    rw [Entourage.pow_zero, Entourage.id_eq, _root_.pow_zero, leftMulEntourage_one]
  | succ n ih =>
    rw [_root_.pow_succ, pow_succ, ih.symm, leftMulEntourage_comp, pow_mul_comm' K n]

@[to_additive]
lemma leftMulEntourage_map_leftMul_subset (g : G) (s : Set G) :
    (leftMulEntourage s).map ⇑(Equiv.mulLeft g) ⊆ leftMulEntourage s := by
  rintro ⟨_, _⟩ ⟨⟨a, b⟩, hab, heq⟩
  obtain ⟨rfl, rfl⟩ := Prod.mk.inj heq
  simpa [mul_inv_rev, mul_assoc] using hab

@[to_additive]
lemma leftMulEntourage_map_conj_subset (g : G) (K : Finset G) :
    (leftMulEntourage K).map ⇑(MulAut.conj g) ⊆
    leftMulEntourage (⇑(MulAut.conj g) '' K) :=
  fun ⟨_, _⟩ ⟨⟨a, b⟩, hab, heq⟩ ↦
    let ⟨hx, hy⟩ := Prod.mk.inj heq
    ⟨a⁻¹ * b, hab, hx ▸ hy ▸ (MulAut.conj g).map_mul a⁻¹ b ▸
      congrArg (· * _) ((MulAut.conj g).map_inv a)⟩

/-! ### Generators and the Left Coarse Structure -/

section Generators

variable (G : Type*) [Group G]

/-- The set of generating entourages for the left multiplication coarse structure on a group `G`.
These are the entourages of the form `leftMulEntourage K` for finite sets `K`. -/
@[to_additive
/-- The set of generating entourages for the left addition coarse structure on an additive
group `G`. These are the entourages of the form `leftAddEntourage K` for finite sets `K`. -/]
def leftMulGenerators : Set (Entourage G) :=
  { E | ∃ K : Finset G, E = leftMulEntourage (K : Set G) }

/-- The canonical coarse structure on a group `G`, generated by left multiplication entourages
of finite sets. -/
@[to_additive
/-- The canonical coarse structure on an additive group `G`, generated by left addition entourages
of finite sets. -/]
instance instCoarseSpaceLeftMulRel : CoarseSpace G :=
  generateFrom (leftMulGenerators G)

end Generators

section Basic

variable {G : Type*} [Group G]

@[to_additive]
lemma leftMulEntourage_mem_leftMulGenerators (K : Finset G) :
  leftMulEntourage K ∈ leftMulGenerators G :=
  ⟨K, rfl⟩

@[to_additive, simp]
lemma isControlled_leftMulEntourage (K : Finset G) :
  IsControlled <| leftMulEntourage (K : Set G) :=
  isControlled_generateFrom_of_mem (leftMulEntourage_mem_leftMulGenerators K)

@[to_additive, simp]
lemma mem_ball_leftMulEntourage {s : Set G} {x y : G} :
  y ∈ (leftMulEntourage s).ball x ↔ y⁻¹ * x ∈ s := by
  rw [Entourage.mem_ball_iff, leftMulEntourage]
  rfl

/-- The ball of `x` in the left multiplication entourage of `s` is the left translate of `s⁻¹`
by `x`. -/
@[to_additive
/-- The ball of `x` in the left addition entourage of `s` is the left translate of `-s` by `x`. -/]
theorem ball_leftMulEntourage (s : Set G) (x : G) :
    (leftMulEntourage s).ball x = Equiv.mulLeft x '' s⁻¹ :=
  Set.ext fun y ↦
    ⟨fun (h : y⁻¹ * x ∈ s) ↦
       ⟨x⁻¹ * y,
        show (x⁻¹ * y)⁻¹ ∈ s by rw [mul_inv_rev, inv_inv]; exact h,
        mul_inv_cancel_left x y⟩,
     fun ⟨g, hg, heq⟩ ↦
       heq ▸ (show (x * g)⁻¹ * x ∈ s from
         mul_inv_rev x g ▸ mul_assoc g⁻¹ x⁻¹ x ▸
         inv_mul_cancel x ▸ (mul_one g⁻¹).symm ▸ mem_inv.mp hg)⟩

open Classical in
/-- Every controlled entourage in the left multiplication coarse structure is contained in
`leftMulEntourage K` for some finite set `K`. -/
@[to_additive
/-- Every controlled entourage in the left addition coarse structure is contained in
`leftAddEntourage K` for some finite set `K`. -/]
theorem exists_finset_leftMulEntourage_of_isControlled {E : Entourage G} (hE : IsControlled E) :
    ∃ K : Finset G, E ⊆ leftMulEntourage K :=
  exists_superset_of_isControlled_generateFrom
    (fun K : Finset G ↦ leftMulEntourage K)
    (fun _ hE ↦ hE.imp fun _ hK ↦ hK.subset)
    ⟨{1}, leftMulEntourage_singleton_one (G := G) ▸
      leftMulEntourage_mono (Finset.singleton_subset_coe.mpr rfl.subset)⟩
    (fun K₁ K₂ ↦ ⟨K₁ ∪ K₂, leftMulEntourage_union (G := G) _ _ ▸
      Finset.coe_union K₁ _ ▸ leftMulEntourage_mono rfl.subset⟩)
    (fun K ↦ ⟨K⁻¹, leftMulEntourage_inv (G := G) _ ▸
      Finset.coe_inv K ▸ leftMulEntourage_mono rfl.subset⟩)
    (fun K₁ K₂ ↦ ⟨K₁ * K₂, leftMulEntourage_comp (G := G) _ _ ▸
      Finset.coe_mul K₁ _ ▸ leftMulEntourage_mono rfl.subset⟩)
    hE

open Classical in
@[to_additive]
theorem exists_finset_leftMulEntourage_of_isControlled_symmetric {E : Entourage G}
    (hE : IsControlled E) :
    ∃ K : Finset G, 1 ∈ K ∧ K = K⁻¹ ∧ E ⊆ leftMulEntourage K :=
  let ⟨K, hK⟩ := exists_finset_leftMulEntourage_of_isControlled hE
  ⟨insert 1 (K ∪ K⁻¹), Finset.mem_insert_self 1 _, Finset.ext_iff.mpr (by simp [or_comm]),
   hK.trans (leftMulEntourage_mono (fun g hg ↦ (by simp only [Finset.coe_insert, Finset.coe_union,
     Finset.coe_inv, mem_insert_iff, mem_union, SetLike.mem_coe, mem_inv]; right; left; exact hg)))⟩

end Basic

variable {G : Type*} [Group G]

/-- Left multiplication by a group element is a controlled map. -/
@[to_additive
/-- Left addition of a group element is a controlled map. -/,
fun_prop]
theorem controlled_leftMul (g : G) :
  Controlled (Equiv.mulLeft g) := by
  refine controlled_generateFrom _ _ ?_
  simp only [leftMulGenerators, mem_setOf_eq,
  forall_exists_index, forall_eq_apply_imp_iff]
  exact fun K ↦ (isControlled_leftMulEntourage K).subset
     <| leftMulEntourage_map_leftMul_subset g ↑K

/-- Left multiplication by a group element is coarsely proper. -/
@[to_additive
/-- Left addition of a group element is coarsely proper. -/,
fun_prop]
theorem coarselyProper_leftMul (g : G) :
  CoarselyProper (Equiv.mulLeft g) :=
  coarselyProper_of_leftInverse
  (leftInverse_inv_mul_mul_right g) (controlled_leftMul g⁻¹)

@[to_additive, fun_prop]
theorem coarse_leftMul (g : G) :
  Coarse (Equiv.mulLeft g) := {}

/-- Left multiplication by `g` as a coarse equivalence of `G`. -/
@[to_additive
/-- Left addition of `g` as a coarse equivalence of `G`. -/]
def leftMulCoarseEquiv (g : G) : G ≃ᶜ G :=
{ toFun := (Equiv.mulLeft g)
  invFun := (Equiv.mulLeft g⁻¹)
  isClose_id_right := isClose_of_eq <| (Equiv.eq_symm_comp _ _ id).mp rfl
  isClose_id_left := isClose_of_eq <| (Equiv.eq_comp_symm _ _ id).mp rfl }

@[to_additive, simp]
lemma leftMulCoarseEquiv_apply (g x : G) :
  leftMulCoarseEquiv g x = g * x :=
  rfl

/-- Conjugation by a group element is a controlled map. -/
@[fun_prop]
theorem controlled_conj (g : G) :
  Controlled (MulAut.conj g) := by
  refine controlled_generateFrom _ _ ?_
  simp only [leftMulGenerators, mem_setOf_eq,
  forall_exists_index, forall_eq_apply_imp_iff]
  intro K
  apply IsControlled.subset _ (leftMulEntourage_map_conj_subset g K)
  have hset :
      (MulAut.conj g '' K) ⊆ K.map (MulAut.conj g : G ↪ G) := by
      intro x h; simpa only [Finset.coe_map, Set.mem_image, SetLike.mem_coe] using h
  exact (isControlled_leftMulEntourage
        (Finset.map ((MulAut.conj g : G ↪ G)) K)).subset (fun p hp ↦ hset hp)

/-- Conjugation by a group element is coarsely proper. -/
@[fun_prop]
theorem coarselyProper_conj (g : G) :
  CoarselyProper (MulAut.conj g) :=
  coarselyProper_of_leftInverse (by intro x; simp [mul_assoc]) (controlled_conj g⁻¹)

@[fun_prop]
theorem coarse_conj (g : G) :
    Coarse (MulAut.conj g) := {}

/-- Conjugation by `g` as a coarse equivalence of `G`. -/
def conjCoarseEquiv (g : G) : G ≃ᶜ G :=
{ toFun := MulAut.conj g,
  invFun := MulAut.conj g⁻¹,
  coarse_invFun := (congrArg (fun f ↦ Coarse f) <| rfl).mpr <| coarse_conj g⁻¹
  isClose_id_right := isClose_of_eq
    <| map_inv (MulAut.conj) g ▸ (MulEquiv.eq_symm_comp _ _ id).mp rfl,
  isClose_id_left := isClose_of_eq
    <| map_inv (MulAut.conj) g ▸ (MulEquiv.eq_symm_comp _ _ id).mp rfl }

@[simp]
lemma conjCoarseEquiv_apply (g x : G) :
  conjCoarseEquiv g x = g * x * g⁻¹ :=
  rfl

@[to_additive]
lemma isCoarselyBounded_of_subset_leftMulEntourage {s : Set G} (K : Finset G)
    (h : s ×ˢ s ⊆ leftMulEntourage K) : IsCoarselyBounded s :=
  ⟨(isControlled_leftMulEntourage K).subset h⟩

section Finite

open Classical in
@[to_additive isCoarselyBounded_of_finset_addGroup]
theorem isCoarselyBounded_of_finset (K : Finset G) :
    IsCoarselyBounded (K : Set G) :=
  isCoarselyBounded_of_subset_leftMulEntourage
    ((K.product K).image fun (p : G × G) ↦ p.1⁻¹ * p.2)
    fun _ ⟨h₁, h₂⟩ ↦ Finset.mem_image.mpr ⟨_, Finset.mem_product.mpr ⟨h₁, h₂⟩, rfl⟩

@[to_additive finite_of_isCoarselyBounded_addGroup]
theorem finite_of_isCoarselyBounded {s : Set G} (hs : IsCoarselyBounded s) : s.Finite :=
  let ⟨K, hK⟩ := exists_finset_leftMulEntourage_of_isControlled hs.isControlled
  s.eq_empty_or_nonempty.elim
  (fun h ↦ h ▸ Set.finite_empty)
  (fun ⟨a, ha⟩ ↦ (K.finite_toSet.image (a * ·)).subset fun b hb ↦
      ⟨a⁻¹ * b, mem_leftMulEntourage.mp (hK ⟨ha, hb⟩), mul_inv_cancel_left a b⟩)

/-- In a group with the left multiplication coarse structure, a set is coarsely bounded if and
only if it is finite. -/
@[to_additive isCoarselyBounded_iff_finite_addGroup
/-- In an additive group with the left addition coarse structure, a set is coarsely bounded if and
only if it is finite. -/]
theorem isCoarselyBounded_iff_finite {s : Set G} : IsCoarselyBounded s ↔ s.Finite :=
  ⟨finite_of_isCoarselyBounded,
   fun hfin ↦ hfin.coe_toFinset ▸ isCoarselyBounded_of_finset hfin.toFinset⟩

/- ### Transporting finite generation from coarse spaces to groups -/

variable [FG G]

/-- A group that is finitely generated as a coarse space is also finitely generated as a group. -/
@[to_additive
/-- An additive group that is finitely generated as a coarse space is also finitely generated as
an additive group. -/]
instance instGroupFG : Group.FG G :=
  let ⟨K, hK1, _, hEK⟩ := exists_finset_leftMulEntourage_of_isControlled_symmetric (G := G)
    (FG.isControlled_getGenerator (X := G))
  ⟨K, (Subgroup.eq_top_iff' _).mpr fun g ↦ by
    let ⟨n, hn⟩ := FG.getGenerator_mem_pow _ (isControlled_leftMulEntourage {g})
    let h1g : (1, g) ∈ leftMulEntourage ({g} : Finset G) :=
      mem_leftMulEntourage.mpr <| (inv_one (G := G)).symm ▸ (one_mul g).symm ▸
        Finset.singleton_subset_set_iff.mp (fun _ a ↦ a)
    let hKn' : (1, g) ∈ leftMulEntourage ((K : Set G) ^ n) :=
      leftMulEntourage_pow (K : Set G) n ▸ pow_mono hEK n (hn h1g)
    let hKn : g ∈ (K : Set G) ^ n := one_mul g ▸ inv_one (G := G) ▸ hKn'
    cases n with
    | zero => exact hKn ▸ Subgroup.one_mem _
    | succ n =>
      exact (Subgroup.closure_pow (Finset.mem_coe.mpr hK1) (Nat.succ_ne_zero n)).symm ▸
            (Subgroup.subset_closure hKn)⟩

end Finite

section Connected

/-- The left multiplication coarse structure on a group is coarsely connected:
every pair `(x, y)` lies in `leftMulEntourage {x⁻¹ * y}`. -/
@[to_additive /--The left addition coarse structure on an additive group is coarsely connected
every pair `(x, y)` lies in `leftAddEntourage {-x + y}`.-/]
instance instCoarselyConnectedSpaceLeftMulRel :
    CoarselyConnectedSpace G where
  isCoarselyConnected_univ := isCoarselyConnected_iff.mpr fun x _ y _ ↦
    ⟨leftMulEntourage ({x⁻¹ * y} : Finset G),
     isControlled_leftMulEntourage {x⁻¹ * y},
     Finset.mem_singleton_self _⟩

end Connected

end CoarseSpace
